# This workflow will do a clean install of node dependencies,
# build the source code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: debian-11

    steps:
      - uses: actions/checkout@v2
      - name: Amerllica Website
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      - run: yarn install
      - run: yarn test
      - run: yarn build
