#name: Amerllica CI
#
#on:
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Amerllica Website
#        uses: actions/setup-node@v2
#        with:
#          node-version: 18.16.0
#      - run: yarn install
#      - run: yarn build
#      - run: yarn test
